### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by cmwall** [cmwall/lsu-classes#12]
Build statistics page.

- Building populations by day / time (average displayed first, then clicking on the building will display by time period)
- Campus wide class population by day / time
- Buildings by average population
- Courses by enrollment count
- Department by enrollment count

- Possibly classes in buildings?

**Comment by cmwall** [comment]
I think this may be what we need to do for display the information: 

- Average can be bar graphs display the population of the building out of the population of the enrolled students total. Time period will be difficult to display other than numbers.
- Campus wide class population - bar graphs displaying population out of total population
- Rank the buildings by number.
- Rank the courses (department abbreviation and class number) by number of enrollments.
- Rank the department abbreviations by enrollment count

**Comment by cmwall** [comment]
I don't think we should do the last one because it would almost be a search bar like classes and instructors and seems a little unnecessary to me.

**Comment by aselle37** [comment]
Ranking courses by enrollment count would be a very long list. How could we efficiently display that?,

**Comment by cmwall** [comment]
True so let's drop that one

**Comment by cmwall** [comment]
Or we can have different pages for the separate departments.

The department page will list all classes in it with their enrollments ranked.
