### ISSUE TITLE
Building Population statistics sorting

### ISSUE THREAD

**Issue by aselle37** [cmwall/lsu-classes#31]
Currently the statistics for building population are not sorted in descending order.

**Comment by cmwall** [comment]
This is because the insertion sorting is happening on the backend instead of the frontend. The items should be sorted on the frontend to ensure their correct order since saving documents isn't always in the right order.

**Comment by cmwall** [comment]
Closed in f3fc7d2f4c366f59d52d5d127c24222647672f82
