### ISSUE TITLE
Search Prompt still being displayed

### ISSUE THREAD

**Issue by aselle37** [cmwall/lsu-classes#32]
Sometimes when searching and then deleting text quickly, the search prompt can be shown along with results. Ex: searching "cs" and then quickly deleting the "s" in the classes tab.

![error](https://cloud.githubusercontent.com/assets/11730277/20693242/a99a53b4-b5a2-11e6-8fc4-6d7519bf8e0d.PNG)

**Comment by cmwall** [comment]
I think this can be fixed by adding a debounce to the search. Now, it searches instantly. If we debounced the search to every .5 seconds or so, it would not be so glitchy.
